spring:
  application:
    name: OrderServiceMS
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://zipkin:9411/
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: "jdbc:h2:mem:productsDb;DB_CLOSE_DELAY=-1"
    username: "sa"
    password: 
    driver-class-name: org.h2.Driver
    
server:
  port: 8071
  
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    metadata-map:
      zone: A
  client:
    fetch-registry: true
    register-with-eureka: true
    prefer-same-zone-eureka: true
    service-url:
      default: http://localhost:8761/eureka
